services:
  - type: web
    name: twitter-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TWITTER_USERNAME
        sync: false
      - key: TWITTER_EMAIL
        sync: false
      - key: TWITTER_PASSWORD
        sync: false
      - key: TWITTER_TOTP_SECRET
        sync: false
      - key: API_KEY
        generateValue: true
      - key: SKIP_TID
        value: 1
